pipeline {
    agent any
    tools {
        maven '3.9.8'
    }
    environment {
        GITHUB_TOKEN = credentials('github_token_id') // Upewnij się, że 'github_token_id' to prawidłowy identyfikator poświadczeń w Jenkins
    }
    stages {
        stage('Check API Rate Limit') { // Dodanie etapu dla skryptu
            steps {
                script {
                    def response = httpRequest(
                        url: 'https://api.github.com/rate_limit',
                        customHeaders: [[name: 'Authorization', value: "token ${env.GITHUB_TOKEN}"]]
                    )
                    echo "Status limitu API GitHub: ${response.content}"
                }
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Finish Build') {
            steps {
                echo "Complete"
            }
        }
    }
}
